import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Download, Mail, Printer, ReceiptText } from "lucide-react";
import { PageHeader, Section } from "@/components/common/page-header";
import { StatusBadge } from "@/components/common/status-badge";
import { EmptyState } from "@/components/common/states";
import { GlassCard, Icon3D, Button3D } from "@/components/common/ui3d";
import { Button } from "@/components/ui/button";
import { invoices, money } from "@/data/seed";

export const Route = createFileRoute("/invoices/$id")({
  component: InvoiceDetail,
  head: () => ({
    meta: [
      { title: "Invoice detail — Ferrolink OSS" },
      { name: "description", content: "Line items, taxes, credits and payment history for a single subscriber invoice." },
      { property: "og:title", content: "Invoice detail — Ferrolink OSS" },
      { property: "og:description", content: "Invoice line items, taxes and payment history." },
    ],
  }),
});

function InvoiceDetail() {
  const { id } = Route.useParams();
  const inv = invoices.find((i) => i.id === id);

  if (!inv) {
    return <EmptyState title="Invoice not found" description="This invoice may have been voided or merged into another billing run." />;
  }

  return (
    <>
      <PageHeader
        title={`Invoice ${inv.number}`}
        subtitle={`${inv.customerName} · issued ${inv.issued} · due ${inv.due}`}
        meta={<StatusBadge value={inv.status} />}
        actions={
          <>
            <Button variant="ghost" size="sm" className="text-xs" asChild>
              <Link to="/invoices"><ArrowLeft className="size-3.5" /> Back</Link>
            </Button>
            <Button variant="outline" size="sm" className="text-xs"><Printer className="size-3.5" /> Print</Button>
            <Button variant="outline" size="sm" className="text-xs"><Download className="size-3.5" /> PDF</Button>
            <Button3D grad="teal" className="h-8 px-3 text-xs"><Mail className="size-3.5" /> Send</Button3D>
          </>
        }
      />
      <div className="grid gap-4 p-4 md:p-6 lg:grid-cols-3">
        <div className="space-y-4 lg:col-span-2">
          <Section title="Line items">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border text-[11px] uppercase tracking-wide text-muted-foreground">
                    <th className="py-2 text-left font-medium">Description</th>
                    <th className="py-2 text-right font-medium">Qty</th>
                    <th className="py-2 text-right font-medium">Rate</th>
                    <th className="py-2 text-right font-medium">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {inv.lines.map((l) => (
                    <tr key={l.description}>
                      <td className="py-2">{l.description}</td>
                      <td className="num py-2 text-right">{l.qty}</td>
                      <td className="num py-2 text-right">{money(l.rate)}</td>
                      <td className="num py-2 text-right font-medium">{money(l.qty * l.rate)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <dl className="mt-4 ml-auto max-w-xs space-y-1.5 text-sm">
              <div className="flex justify-between"><dt className="text-muted-foreground">Subtotal</dt><dd className="num">{money(inv.subtotal)}</dd></div>
              <div className="flex justify-between"><dt className="text-muted-foreground">Taxes & fees</dt><dd className="num">{money(inv.tax)}</dd></div>
              <div className="flex justify-between border-t border-border pt-1.5 font-semibold"><dt>Total due</dt><dd className="num">{money(inv.total)}</dd></div>
            </dl>
          </Section>

          <Section title="Payment activity">
            <ol className="space-y-3 text-sm">
              {[
                { t: inv.issued, a: "Invoice generated by recurring billing run" },
                { t: inv.issued, a: "Invoice emailed to account contact" },
                ...(inv.status === "paid" ? [{ t: inv.due, a: "Payment settled in full" }] : []),
                ...(inv.status === "overdue" ? [{ t: inv.due, a: "Dunning stage 1 notice sent" }] : []),
              ].map((e, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1 size-2 shrink-0 rounded-full bg-primary" />
                  <div>
                    <p>{e.a}</p>
                    <p className="text-xs text-muted-foreground">{e.t}</p>
                  </div>
                </li>
              ))}
            </ol>
          </Section>
        </div>

        <div className="space-y-4">
          <GlassCard className="space-y-3">
            <div className="flex items-center gap-3">
              <Icon3D icon={ReceiptText} grad="violet" size="lg" />
              <div>
                <p className="text-[11px] uppercase tracking-wide text-muted-foreground">Amount due</p>
                <p className="num text-2xl font-semibold">{money(inv.status === "paid" ? 0 : inv.total)}</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <Button3D grad="emerald" className="h-9 text-xs">Take payment</Button3D>
              <Button3D grad="amber" className="h-9 text-xs">Apply credit</Button3D>
              <Button3D grad="slate" className="h-9 text-xs">Payment plan</Button3D>
              <Button3D grad="rose" className="h-9 text-xs">Void invoice</Button3D>
            </div>
          </GlassCard>

          <Section title="Bill to">
            <p className="text-sm font-medium">{inv.customerName}</p>
            <Link to="/customers/$id" params={{ id: inv.customerId }} className="text-xs text-primary hover:underline">
              Open customer 360 →
            </Link>
          </Section>
        </div>
      </div>
    </>
  );
}
