/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DunningRouteImport } from './routes/dunning'
import { Route as IpamRouteImport } from './routes/ipam'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as OnuRouteImport } from './routes/onu'
import { Route as PaymentPlansRouteImport } from './routes/payment-plans'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProvisioningRouteImport } from './routes/provisioning'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsIdRouteImport } from './routes/tickets/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DunningRoute = DunningRouteImport.update({
  id: '/dunning',
  path: '/dunning',
  getParentRoute: () => rootRouteImport,
} as any)
const IpamRoute = IpamRouteImport.update({
  id: '/ipam',
  path: '/ipam',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OnuRoute = OnuRouteImport.update({
  id: '/onu',
  path: '/onu',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPlansRoute = PaymentPlansRouteImport.update({
  id: '/payment-plans',
  path: '/payment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisioningRoute = ProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/contracts': typeof ContractsRoute
  '/devices': typeof DevicesRoute
  '/dispatch': typeof DispatchRoute
  '/dunning': typeof DunningRoute
  '/ipam': typeof IpamRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/onu': typeof OnuRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/plans': typeof PlansRoute
  '/provisioning': typeof ProvisioningRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/taxes': typeof TaxesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/contracts': typeof ContractsRoute
  '/devices': typeof DevicesRoute
  '/dispatch': typeof DispatchRoute
  '/dunning': typeof DunningRoute
  '/ipam': typeof IpamRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/onu': typeof OnuRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/plans': typeof PlansRoute
  '/provisioning': typeof ProvisioningRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/taxes': typeof TaxesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/contracts': typeof ContractsRoute
  '/devices': typeof DevicesRoute
  '/dispatch': typeof DispatchRoute
  '/dunning': typeof DunningRoute
  '/ipam': typeof IpamRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/onu': typeof OnuRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/plans': typeof PlansRoute
  '/provisioning': typeof ProvisioningRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/taxes': typeof TaxesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complaints'
    | '/contracts'
    | '/devices'
    | '/dispatch'
    | '/dunning'
    | '/ipam'
    | '/jobs'
    | '/leads'
    | '/ledger'
    | '/login'
    | '/network'
    | '/onu'
    | '/payment-plans'
    | '/payments'
    | '/pipeline'
    | '/plans'
    | '/provisioning'
    | '/reports'
    | '/stock'
    | '/subscriptions'
    | '/taxes'
    | '/customers/$id'
    | '/invoices/$id'
    | '/tickets/$id'
    | '/customers/'
    | '/invoices/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complaints'
    | '/contracts'
    | '/devices'
    | '/dispatch'
    | '/dunning'
    | '/ipam'
    | '/jobs'
    | '/leads'
    | '/ledger'
    | '/login'
    | '/network'
    | '/onu'
    | '/payment-plans'
    | '/payments'
    | '/pipeline'
    | '/plans'
    | '/provisioning'
    | '/reports'
    | '/stock'
    | '/subscriptions'
    | '/taxes'
    | '/customers/$id'
    | '/invoices/$id'
    | '/tickets/$id'
    | '/customers'
    | '/invoices'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/complaints'
    | '/contracts'
    | '/devices'
    | '/dispatch'
    | '/dunning'
    | '/ipam'
    | '/jobs'
    | '/leads'
    | '/ledger'
    | '/login'
    | '/network'
    | '/onu'
    | '/payment-plans'
    | '/payments'
    | '/pipeline'
    | '/plans'
    | '/provisioning'
    | '/reports'
    | '/stock'
    | '/subscriptions'
    | '/taxes'
    | '/customers/$id'
    | '/invoices/$id'
    | '/tickets/$id'
    | '/customers/'
    | '/invoices/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ContractsRoute: typeof ContractsRoute
  DevicesRoute: typeof DevicesRoute
  DispatchRoute: typeof DispatchRoute
  DunningRoute: typeof DunningRoute
  IpamRoute: typeof IpamRoute
  JobsRoute: typeof JobsRoute
  LeadsRoute: typeof LeadsRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  OnuRoute: typeof OnuRoute
  PaymentPlansRoute: typeof PaymentPlansRoute
  PaymentsRoute: typeof PaymentsRoute
  PipelineRoute: typeof PipelineRoute
  PlansRoute: typeof PlansRoute
  ProvisioningRoute: typeof ProvisioningRoute
  ReportsRoute: typeof ReportsRoute
  StockRoute: typeof StockRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TaxesRoute: typeof TaxesRoute
  CustomersIdRoute: typeof CustomersIdRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunning': {
      id: '/dunning'
      path: '/dunning'
      fullPath: '/dunning'
      preLoaderRoute: typeof DunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipam': {
      id: '/ipam'
      path: '/ipam'
      fullPath: '/ipam'
      preLoaderRoute: typeof IpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onu': {
      id: '/onu'
      path: '/onu'
      fullPath: '/onu'
      preLoaderRoute: typeof OnuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-plans': {
      id: '/payment-plans'
      path: '/payment-plans'
      fullPath: '/payment-plans'
      preLoaderRoute: typeof PaymentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning': {
      id: '/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof ProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintsRoute: ComplaintsRoute,
  ContractsRoute: ContractsRoute,
  DevicesRoute: DevicesRoute,
  DispatchRoute: DispatchRoute,
  DunningRoute: DunningRoute,
  IpamRoute: IpamRoute,
  JobsRoute: JobsRoute,
  LeadsRoute: LeadsRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  OnuRoute: OnuRoute,
  PaymentPlansRoute: PaymentPlansRoute,
  PaymentsRoute: PaymentsRoute,
  PipelineRoute: PipelineRoute,
  PlansRoute: PlansRoute,
  ProvisioningRoute: ProvisioningRoute,
  ReportsRoute: ReportsRoute,
  StockRoute: StockRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TaxesRoute: TaxesRoute,
  CustomersIdRoute: CustomersIdRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
