/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DunningRouteImport } from './routes/dunning'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PaymentPlansRouteImport } from './routes/payment-plans'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProvisioningRouteImport } from './routes/provisioning'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StockRouteImport } from './routes/stock'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsIdRouteImport } from './routes/tickets/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DunningRoute = DunningRouteImport.update({
  id: '/dunning',
  path: '/dunning',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPlansRoute = PaymentPlansRouteImport.update({
  id: '/payment-plans',
  path: '/payment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisioningRoute = ProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/dunning': typeof DunningRoute
  '/ledger': typeof LedgerRoute
  '/network': typeof NetworkRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/payments': typeof PaymentsRoute
  '/provisioning': typeof ProvisioningRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/taxes': typeof TaxesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/dunning': typeof DunningRoute
  '/ledger': typeof LedgerRoute
  '/network': typeof NetworkRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/payments': typeof PaymentsRoute
  '/provisioning': typeof ProvisioningRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/taxes': typeof TaxesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/dunning': typeof DunningRoute
  '/ledger': typeof LedgerRoute
  '/network': typeof NetworkRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/payments': typeof PaymentsRoute
  '/provisioning': typeof ProvisioningRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/taxes': typeof TaxesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatch'
    | '/dunning'
    | '/ledger'
    | '/network'
    | '/payment-plans'
    | '/payments'
    | '/provisioning'
    | '/reports'
    | '/stock'
    | '/taxes'
    | '/customers/$id'
    | '/invoices/$id'
    | '/tickets/$id'
    | '/customers/'
    | '/invoices/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatch'
    | '/dunning'
    | '/ledger'
    | '/network'
    | '/payment-plans'
    | '/payments'
    | '/provisioning'
    | '/reports'
    | '/stock'
    | '/taxes'
    | '/customers/$id'
    | '/invoices/$id'
    | '/tickets/$id'
    | '/customers'
    | '/invoices'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/dispatch'
    | '/dunning'
    | '/ledger'
    | '/network'
    | '/payment-plans'
    | '/payments'
    | '/provisioning'
    | '/reports'
    | '/stock'
    | '/taxes'
    | '/customers/$id'
    | '/invoices/$id'
    | '/tickets/$id'
    | '/customers/'
    | '/invoices/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispatchRoute: typeof DispatchRoute
  DunningRoute: typeof DunningRoute
  LedgerRoute: typeof LedgerRoute
  NetworkRoute: typeof NetworkRoute
  PaymentPlansRoute: typeof PaymentPlansRoute
  PaymentsRoute: typeof PaymentsRoute
  ProvisioningRoute: typeof ProvisioningRoute
  ReportsRoute: typeof ReportsRoute
  StockRoute: typeof StockRoute
  TaxesRoute: typeof TaxesRoute
  CustomersIdRoute: typeof CustomersIdRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunning': {
      id: '/dunning'
      path: '/dunning'
      fullPath: '/dunning'
      preLoaderRoute: typeof DunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-plans': {
      id: '/payment-plans'
      path: '/payment-plans'
      fullPath: '/payment-plans'
      preLoaderRoute: typeof PaymentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning': {
      id: '/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof ProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispatchRoute: DispatchRoute,
  DunningRoute: DunningRoute,
  LedgerRoute: LedgerRoute,
  NetworkRoute: NetworkRoute,
  PaymentPlansRoute: PaymentPlansRoute,
  PaymentsRoute: PaymentsRoute,
  ProvisioningRoute: ProvisioningRoute,
  ReportsRoute: ReportsRoute,
  StockRoute: StockRoute,
  TaxesRoute: TaxesRoute,
  CustomersIdRoute: CustomersIdRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
